export const AUTH_ERROR = 'AUTH_ERROR';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';

export const REGISTER_FAIL = 'REGISTER_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const USER_LOADED = 'USER_LOADED';
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';

export const REMOVE_ALERT = 'REMOVE_ALERT';
export const SET_ALERT = 'SET_ALERT';

export const GET_LISTS = 'GET_LISTS';
export const LISTS_ERROR = 'LISTS_ERROR';
export const GET_LIST = 'GET_LIST';
export const UPDATE_LIST = 'UPDATE_LIST';
export const REMOVE_LIST = 'REMOVE_LIST';
export const TOGGLE_LIST_INGREDIENT = 'TOGGLE_LIST_INGREDIENT';

export const SET_DATA_URI = 'SET_DATA_URI';
export const REMOVE_DATA_URI = 'REMOVE_DATA_URI';
export const SET_CLOUDINARY_URI = 'SET_CLOUDINARY_URI';
export const SUBMITTED_IMAGE = 'SUBMITTED_IMAGE';
export const RESET_SUBMITTED_IMAGE = 'RESET_SUBMITTED_IMAGE';

export const INGREDIENTS_FETCHED = 'INGREDIENTS_FETCHED';
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const RESET_INGREDIENTS = 'RESET_INGREDIENTS';

export const TO_SUBMIT_LIST = 'TO_SUBMIT_LIST';
export const SUBMIT_LIST_SUCCESS = 'SUBMIT_LIST_SUCCESS';
export const SUBMIT_LIST_FAIL = 'SUBMIT_LIST_FAIL';

export const HAMBURGER_OPEN = 'HAMBURGER_OPEN';
export const HAMBURGER_CLOSE = 'HAMBURGER_CLOSE';

export const SET_WIDTH = 'SET_WIDTH';
